dir: enchup
temp: enchup/tmp
template_dir: enchup/templates

config: enchup/enchup.yml

tree:
  - [file, enchup.yml, true]
  - [file, README.md]
  - [dir, templates/repo]

repository: tuchk4/enchup-simple-struct



