dir: enchup
temp: enchup/tmp
template_dir: enchup/templates
scripts: enchup/post-scripts

app-config: enchup/enchup.yml
user-config: enchup/user-enchup.yml

# type: file | dir
# path
# save current copy. Only for files
tree:
  - [file, enchup/enchup.yml, true]
  - [file, enchup/README.md]
  - [dir, enchup/templates/repo]

repository:
  setup: tuchk4/enchup-simple-struct



