dir: enchup
temp: enchup/tmp
template_dir: enchup/templates
scripts: enchup/post-scripts

app-config: enchup/enchup.yml
user-config: enchup/user-enchup.yml
build-config: enchup/build-enchup.yml

tree:
  - [file, enchup.yml, true]
  - [file, README.md]
  - [dir, templates/repo]

repository: tuchk4/enchup-simple-struct



