dir: enchup
temp: enchup/tmp
template_dir: enchup/templates
scripts: enchup/post-scripts

configs:
  app: enchup/enchup.yml
  user: enchup/user-enchup.yml

# type: file | dir
# path
# save current copy. Only for files
#tree:
#  - [file, enchup/enchup.yml, true]
#  - [file, enchup/README.md]
#  - [dir, enchup/templates/repo]

#repository:
#  setup: frankland/enchup-js-struct
#  init: frankland/valent-boilerplate



